require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.9
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config.ru'
    - 'bin/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'node_modules/**/*'

# Rails specific cops
Rails:
  Enabled: true

# RSpec specific cops
RSpec:
  Enabled: true

# Customize specific cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 8

RSpec/NestedGroups:
  Max: 4
